# NUMPY UNIVERSAL FUNCTIONS

In [86]:
import numpy as np

### MATH OPERATIONS

In [87]:
arr1 = np.array([1,2,3])
arr2 = np.array([2,4,6])

# MULTIPLY => Add arguments element wise

np.multiply(arr1,arr2)

array([ 2,  8, 18])

In [88]:
arr3 = np.array([1/4, 8, 4/12])

# RECIPROCAL => Return the reciprocal of the argument element-wise

np.reciprocal(arr3)

array([4.   , 0.125, 3.   ])

In [89]:
arr4 = np.array([2.4, 8.7, 10/3])

# RINT => Round elements of the array to the nearest integer

np.rint(arr4)

array([2., 9., 3.])

In [90]:
arr5 = np.array([2,4,6,8])
arr6 = np.array([6,14,18,28])

# FMOD => Returns the element-wise remainder of division

np.fmod(arr5,arr5/arr6)


array([1.11022302e-16, 2.22044605e-16, 3.33066907e-16, 4.44089210e-16])

### TRIGONOMETRIC FUNCTIONS

In [91]:
arr7 = np.array([0,90,180,270,360])

# COS => Cosine element-wise

np.cos(arr7)

array([ 1.        , -0.44807362, -0.59846007,  0.98438195, -0.28369109])

In [92]:
arr8 = np.array([0,90,180,270,360])

# ARCTAN => Trigonometric inverse tangent, element-wise

np.arctan(arr8)

array([0.        , 1.55968567, 1.56524083, 1.56709264, 1.56801856])

In [93]:
arr9 = np.array([0,90,180,270,360])

# RADIANS => Convert angles from degrees to radians

np.radians(arr9)

array([0.        , 1.57079633, 3.14159265, 4.71238898, 6.28318531])

In [94]:
base = 2
perp = 4

# HYPOT => Given the "legs" of a right triangle, return its hypotenuse

np.hypot(base,perp)

4.47213595499958

### BIT-TWIDDLING FUNCTIONS

In [95]:
a = np.array([1,0,0,0,1])
b = np.array([False,False,True,True,True])

# BITWISE_AND => Compute the bit-wise AND of two arrays element-wise

np.bitwise_and(a,b)

array([0, 0, 0, 0, 1], dtype=int32)

In [96]:
c = np.array([True,False,False,False,True])
d = np.array([False,False,True,True,True])

# BITWISE_XOR => Compute the bit-wise XOR of two arrays element-wise

np.bitwise_xor(c,d)

array([ True, False,  True,  True, False])

In [97]:
e = np.array([False,False,True,True,True])
f = np.array([0,1,0,0,1])

# INVERT => Compute bit-wise inversion, or bit-wise NOT, element-wise

display(np.invert(e))
display(np.invert(f))

array([ True,  True, False, False, False])

array([-1, -2, -1, -1, -2], dtype=int32)

In [98]:
g = 5
h = np.array([1,8,0,7,1])

# RIGHT_SHIFT => Shift the bits of an integer to the right

np.right_shift(g,h)

array([2, 0, 5, 0, 2], dtype=int32)

### COMPARISON FUNCTIONS

In [99]:
i = 20
ii = 25

# GREATER => Return the truth value of (x1 > x2) element-wise

np.greater(i,ii)

False

In [100]:
iii = 22
iv = 25

# LESS_EQUAL => Return the truth value of (x1 <= x2) element-wise

np.less_equal(iii,iv)

True

In [101]:
v = np.array([1,0,0,0,1])
vi = np.array([0,0,1,1,1])

# LOGICAL_XOR => Compute the truth value of x1 XOR x2, element-wise

np.logical_xor(v,vi)

array([ True, False,  True,  True, False])

In [102]:
vii = np.array([2,1,23,40,14,21])
viii = np.array([8,3,91,18,37,26])

# FMAX => Element-wise maximum of array elements

np.fmax(vii,viii)

array([ 8,  3, 91, 40, 37, 26])

### FLOATING FUNCTIONS

In [103]:
import math
a = np.array([2,math.nan,0,4,8])

# ISNAN => Test element-wise for NaN and return result as a boolean array

np.isnan(a)

array([False,  True, False, False, False])

In [104]:
b = np.array([-4,-2,0,2,4])

# SIGNBIT => Returns element-wise True where signbit is set (less than zero)

np.signbit(b)

array([ True,  True, False, False, False])

In [105]:
c = np.array([-4.4,-2.8,0.1,2.5,4.6])

# CEIL => Return the ceiling of the input, element-wise

np.ceil(c)

array([-4., -2.,  1.,  3.,  5.])

In [106]:
d = np.array([-4.4,-2.8,0.1,2.5,4.6])

# TRUNC => Return the truncated value of the input, element-wise

np.trunc(d)

array([-4., -2.,  0.,  2.,  4.])